add .name_repair
Trying to avoid error in checks:
(still not working)
- Quitting from lines 271-273 [unnamed-chunk-28] (guide.Rmd)
   Error: processing vignette 'guide.Rmd' failed with diagnostics:
   The `validate` argument of
 `as_tibble()` was deprecated in tibble 2.0.0
   and is now defunct.
  Please use the `.name_repair` argument instead.